plugins {
    id 'com.android.application'
}

android {
    compileSdk 34 // Updated to 34 (Android 14)

    defaultConfig {
        applicationId "com.aniketjain.weatherapp"
        minSdk 21
        targetSdk 34 // Updated to 34
        versionCode 5
        versionName "1.0.5"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures { viewBinding true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // 🔥 YAHAN CHANGE KIYA HAI (1.12.2 ko 1.8.0 kar diya hai taake error khatam ho jaye)
    implementation 'androidx.activity:activity:1.8.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Volley
    implementation 'com.android.volley:volley:1.2.1'
    // Location
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    // Custom Toast & Progress
    implementation 'com.github.dev-aniketj:roasted-toast:1.0.2'
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    // Swipe Refresh
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    // App Auto Update (Correct Library)
    implementation 'com.google.android.play:app-update:2.1.0'

    // SDP & Lottie
    implementation 'com.intuit.sdp:sdp-android:1.1.0'
    implementation 'com.airbnb.android:lottie:5.2.0'
    // MultiDex
    implementation 'androidx.multidex:multidex:2.0.1'

    // Google Ads (Correctly placed)
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}